###
POST http://localhost:3000/api/agregar2 HTTP/1.1
Content-Type: application/json

{
    "codigo": 10589234,
    "subcat_id": 1,
    "marca": "Brembo",
    "nombre": "Tornillo CRS Punta Fina 1P",
    "precio": 2590
}

###
GET http://localhost:3000/api HTTP/1.1


###
GET http://localhost:3000/api/stock/1
