###
POST http://localhost:3000/api/agregar HTTP/1.1
Content-Type: application/json

{
    "codigo": 84923,
    "subcat": 2,
    "marca": "Philips",
    "nombre": "Martillo Pecutor",
    "precio": 12990,
    "stock": {
        "stock1": 12,
        "stock2": 3
    }

}

###
GET http://localhost:3000/api HTTP/1.1

